name: "Wiredoor Tunnel"
slug: wiredoor
description: "Expose Home Assistant securely using Wiredoor"
version: "1.0.0"
url: "https://github.com/wiredoor/home-assistant-wiredoor-addon/tree/main/wiredoor"
arch:
  - aarch64
  - amd64
  - armv7
# startup: services
# boot: auto
# host_network: true
# hassio_api: true
init: false
privileged:
  - NET_ADMIN
options:
  url: ""
  token: ""
schema:
  url: str
  token: password